example_roulette: roulette.Wheel Class Reference
roulette.Wheel Class Reference
Public Member Functions
Wheel ()
String getColor ()
int getNumber ()
int getNumSpins ()
void spin ()
Static Public Attributes
static final String RED = "red"
static final String BLACK = "black"
static final String GREEN = "green"
static final int NUM_SPOTS = OUR_SPOTS.length
Private Attributes
int myNumSpins
int myValue
Random myRoller
Static Private Attributes
static final String[] OUR_SPOTS
Detailed Description
Represents a roulette wheel that can be spun to get a color, either red, black, or green, and a number, between 0 and 37. The numbers 0 and 37 represent the roulette values 0 and 00, respectively.
Author
Robert C. Duvall
Definition at line 13 of file Wheel.java.
Constructor & Destructor Documentation
roulette.Wheel.Wheel ()
Construct the wheel.
Definition at line 69 of file Wheel.java.
Member Function Documentation
String roulette.Wheel.getColor ()
Returns
color of the current spot on the wheel
Definition at line 79 of file Wheel.java.
References roulette.Wheel.myValue.
Referenced by roulette.RedBlack.isMade(), and roulette.Game.play().
int roulette.Wheel.getNumber ()
Returns
number of the current spot on the wheel
Definition at line 86 of file Wheel.java.
References roulette.Wheel.myValue.
Referenced by roulette.OddEven.isMade(), roulette.ThreeConsecutive.isMade(), and roulette.Game.play().
int roulette.Wheel.getNumSpins ()
Returns
number of times the wheel has been spun
Definition at line 93 of file Wheel.java.
References roulette.Wheel.myNumSpins.
void roulette.Wheel.spin ()
Spins the wheel, choosing a new spot.
Definition at line 100 of file Wheel.java.
Referenced by roulette.Game.play().
Member Data Documentation
final String roulette.Wheel.BLACK = "black" static
Definition at line 16 of file Wheel.java.
Referenced by roulette.RedBlack.place().
final String roulette.Wheel.GREEN = "green" static
Definition at line 17 of file Wheel.java.
int roulette.Wheel.myNumSpins private
Definition at line 61 of file Wheel.java.
Referenced by roulette.Wheel.getNumSpins().
Random roulette.Wheel.myRoller private
Definition at line 63 of file Wheel.java.
int roulette.Wheel.myValue private
Definition at line 62 of file Wheel.java.
Referenced by roulette.Wheel.getColor(), and roulette.Wheel.getNumber().
final int roulette.Wheel.NUM_SPOTS = OUR_SPOTS.length static
Definition at line 59 of file Wheel.java.
final String [] roulette.Wheel.OUR_SPOTS static private
Definition at line 19 of file Wheel.java.
final String roulette.Wheel.RED = "red" static
Definition at line 15 of file Wheel.java.
Referenced by roulette.RedBlack.place().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_roulette/repository/src/roulette/Wheel.java