example_roulette: util.ConsoleReader Class Reference
util.ConsoleReader Class Reference
Static Public Member Functions
static String promptString (String prompt)
static int promptInt (String prompt)
static double promptDouble (String prompt)
static int promptRange (String prompt, int low, int hi)
static String promptOneOf (String prompt, String...choices)
Static Private Attributes
static Scanner in = new Scanner(new InputStreamReader(System.in))
Detailed Description
Provides variety of methods to simplify getting user input from console.
Author
Robert C. Duvall
Definition at line 15 of file ConsoleReader.java.
Member Function Documentation
static double util.ConsoleReader.promptDouble (String prompt) static
Prompts the user to input an real value.
Parameters
prompt output to the user before waiting for input
Returns
the value entered, waiting if necessary until one is given
Definition at line 56 of file ConsoleReader.java.
References util.ConsoleReader.promptString().
static int util.ConsoleReader.promptInt (String prompt) static
Prompts the user to input an integer value.
Parameters
prompt output to the user before waiting for input
Returns
the value entered, waiting if necessary until one is given
Definition at line 36 of file ConsoleReader.java.
References util.ConsoleReader.promptString().
Referenced by util.ConsoleReader.promptRange().
static String util.ConsoleReader.promptOneOf (String prompt, String... choices) static
Prompts the user to input one of the given choices to the question.
Note, repeatedly prompts the user until a valid choice is entered.
Parameters
prompt output to the user before waiting for input
choices possible valid responses user can enter
Returns
the value entered, waiting if necessary until one is given
Definition at line 99 of file ConsoleReader.java.
References util.ConsoleReader.promptString().
Referenced by roulette.bets.OddEven.place(), and roulette.bets.RedBlack.place().
static int util.ConsoleReader.promptRange (String prompt, int low, int hi) static
Prompts the user to input an integer value between the given values, inclusive.
Note, repeatedly prompts the user until a valid value is entered.
Parameters
prompt output to the user before waiting for input
low minimum possible valid value allowed
hi maximum possible valid value allowed
Returns
the value entered, waiting if necessary until one is given
Definition at line 80 of file ConsoleReader.java.
References util.ConsoleReader.promptInt().
Referenced by roulette.bets.ThreeConsecutive.place(), roulette.Game.play(), and roulette.Game.promptForBet().
static String util.ConsoleReader.promptString (String prompt) static
Prompts the user to input a word.
Parameters
prompt output to the user before waiting for input
Returns
the value entered, waiting if necessary until one is given
Definition at line 25 of file ConsoleReader.java.
Referenced by util.ConsoleReader.promptDouble(), util.ConsoleReader.promptInt(), and util.ConsoleReader.promptOneOf().
Member Data Documentation
Scanner util.ConsoleReader.in = new Scanner(new InputStreamReader(System.in)) static private
Definition at line 17 of file ConsoleReader.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_roulette/repository/src/util/ConsoleReader.java