example_roulette: roulette.Gambler Class Reference
roulette.Gambler Class Reference
Public Member Functions
Gambler (String name, int money)
String getName ()
int getBankroll ()
boolean isSolvent ()
void updateBankroll (int amount)
Private Attributes
String myName
int myMoney
Detailed Description
Represents a Gambler simply as an amount to money to be spent.
Author
Robert C. Duvall
Definition at line 9 of file Gambler.java.
Constructor & Destructor Documentation
roulette.Gambler.Gambler (String name, int money)
Constructs a gambler with the given name and an initial bankroll.
Parameters
name used to refer to the gambler
money initial amount of the money the gambler has to spend
Definition at line 19 of file Gambler.java.
Member Function Documentation
int roulette.Gambler.getBankroll ()
Returns
amount of money the gambler has left
Definition at line 34 of file Gambler.java.
References roulette.Gambler.myMoney.
Referenced by roulette.Game.play().
String roulette.Gambler.getName ()
Returns
name of the gambler
Definition at line 27 of file Gambler.java.
References roulette.Gambler.myName.
Referenced by Main.main().
boolean roulette.Gambler.isSolvent ()
Returns
true if the gambler has money left to spend, false otherwise
Definition at line 41 of file Gambler.java.
Referenced by Main.main().
void roulette.Gambler.updateBankroll (int amount)
Changes the gambler's bankroll to reflect the given amount won or lost.
Parameters
amount money won (positive) or lost (negative) by the gambler
Definition at line 50 of file Gambler.java.
Referenced by roulette.Game.play().
Member Data Documentation
int roulette.Gambler.myMoney private
Definition at line 11 of file Gambler.java.
Referenced by roulette.Gambler.getBankroll().
String roulette.Gambler.myName private
Definition at line 10 of file Gambler.java.
Referenced by roulette.Gambler.getName().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_roulette/repository/src/roulette/Gambler.java