example_roulette: roulette.Bet Class Reference
roulette.Bet Class Reference abstract
Public Member Functions
Bet (String description, int odds)
int getOdds ()
String getDescription ()
abstract String place ()
abstract boolean isMade (String betChoice, Wheel wheel)
Private Attributes
String myDescription
int myOdds
Detailed Description
Represents player's attempt to bet on outcome of the roulette wheel's spin.
Author
Robert C. Duvall
Definition at line 9 of file Bet.java.
Constructor & Destructor Documentation
roulette.Bet.Bet (String description, int odds)
Constructs a bet with the given name and odds.
Parameters
description name of this kind of bet
odds odds given by the house for this kind of bet
Definition at line 19 of file Bet.java.
Member Function Documentation
String roulette.Bet.getDescription ()
Returns
name of this kind of bet
Definition at line 34 of file Bet.java.
References roulette.Bet.myDescription.
Referenced by roulette.Game.promptForBet().
int roulette.Bet.getOdds ()
Returns
odds given by the house for this kind of bet
Definition at line 27 of file Bet.java.
References roulette.Bet.myOdds.
Referenced by roulette.Game.play().
abstract boolean roulette.Bet.isMade (String betChoice, Wheel wheel) abstract
Checks if bet is won or lost given the user's choice and result of spinning the wheel.
Parameters
betChoice specific value user chose to try to win the bet
wheel information needed to check if bet won or lost
Referenced by roulette.Game.play().
abstract String roulette.Bet.place () abstract
Place bet by prompting user for the specific information need to complete this bet.
Referenced by roulette.Game.play().
Member Data Documentation
String roulette.Bet.myDescription private
Definition at line 10 of file Bet.java.
Referenced by roulette.Bet.getDescription().
int roulette.Bet.myOdds private
Definition at line 11 of file Bet.java.
Referenced by roulette.Bet.getOdds().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_roulette/repository/src/roulette/Bet.java