example_roulette: roulette.Game Class Reference
roulette.Game Class Reference
Public Member Functions
Game ()
String getName ()
void play (Gambler player)
Private Member Functions
Bet promptForBet ()
Private Attributes
Bet[] myPossibleBets
Wheel myWheel
Static Private Attributes
static final String DEFAULT_NAME = "Roulette"
Detailed Description
Plays a game of roulette.
Author
Robert C. Duvall
Definition at line 14 of file Game.java.
Constructor & Destructor Documentation
roulette.Game.Game ()
Construct the game.
Definition at line 28 of file Game.java.
Member Function Documentation
String roulette.Game.getName ()
Returns
name of the game
Definition at line 35 of file Game.java.
References roulette.Game.DEFAULT_NAME.
Referenced by Main.main().
void roulette.Game.play (Gambler player)
Play a round of roulette.
Prompt player to make a bet, then spin the roulette wheel, and then verify that the bet is won or lost.
Parameters
player one that wants to play a round of the game
Definition at line 47 of file Game.java.
References roulette.Gambler.getBankroll(), roulette.Bet.isMade(), roulette.Bet.payout(), roulette.Bet.place(), roulette.Game.promptForBet(), util.ConsoleReader.promptRange(), roulette.Wheel.spin(), and roulette.Gambler.updateBankroll().
Referenced by Main.main().
Bet roulette.Game.promptForBet () private
Prompt the user to make a bet from a menu of choices.
Definition at line 70 of file Game.java.
References util.ConsoleReader.promptRange().
Referenced by roulette.Game.play().
Member Data Documentation
final String roulette.Game.DEFAULT_NAME = "Roulette" static private
Definition at line 16 of file Game.java.
Referenced by roulette.Game.getName().
Bet [] roulette.Game.myPossibleBets private
Initial value:
= {
        new RedBlack("Red or Black", 1),
        new OddEven("Odd or Even", 1),
        new ThreeConsecutive("Three in a Row", 11),
    }
Definition at line 18 of file Game.java.
Wheel roulette.Game.myWheel private
Definition at line 23 of file Game.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_roulette/repository/src/roulette/Game.java